re_split: false

lr: 1e-3
n_epochs: 4000
weight_decay: 5e-4
patience: 100

backbone: gcn
n_hidden: 16
dropout: 0.5
input_dropout: 0.0   # cora:0.8,citeseer:0.0
norm: false

symmetric: true
lambda_: 0
alpha: 0
beta: 0
gamma: 0.3
lr_adj: 1e-2
inner_steps: 2
outer_steps: 1
only_gcn: false
eta: 0.5

#lpcls: 5

# below is for saving results
save_graph: false
